       SUBROUTINE CREEP(DECRA,DESWA,STATEV,SERD,EC,ESW,P,QTILD
     1 TEMP,DTEMP,PREDEF,DPRED,TIME,DTIME,CMNAME,LEXIMP,LEND,
     2 COORDS,NSTATV,NOEL,NPT,LAYER,KSPT,KSTEP,KINC)
C
       INCLUDE 'ABA_PARAM.INC'
C
       CHARACTER*80 CMNAME
C
       DIMENSION DECRA(5),DESWA(5),STATEV(4),PREDEF(5),DPRED(5),
     1 TIME(2),EC(2),ESW(2),COORDS(5),SMETAL(13),DYDX(3)
c      SMETAL(13),DYDX(3)
       REAL*8 D1,Tab,RIP
c      REAL*8 RIP
     


      
          DECRA(1)=0.5*DTIME
      
       RETURN
       END
