clear;

NatNode=[...
    1 1 1;...
    1 -1 1;...
    1 1 -1;...
    1 -1 -1;...
    -1 1 1;...
    -1 -1 1;...
    -1 1 -1;...
    -1 -1 -1;...
    ];

GaussNatNode=(1./sqrt(3)).*NatNode;

NodesReal=[...
    2 3 1;...
    2 0 1;...
    2 3 0;...
    2 0 0;...
    0 3 1;...
    0 0 1;...
    0 3 0;...
    0 0 0;...
    ];

NodesReal=[...
    1 1 1;...
    1 0 1;...
    1 1 0;...
    1 0 0;...
    0 1 1;...
    0 0 1;...
    0 1 0;...
    0 0 0;...
    ];

%%
figure(1);
clf;
hold on;
plot3(NatNode(:,1),NatNode(:,2),NatNode(:,3),'bo');
plot3(GaussNatNode(:,1),GaussNatNode(:,2),GaussNatNode(:,3),'rx');

axis equal;

figure(2);
clf;
hold on;
plot3(NodesReal(:,1),NodesReal(:,2),NodesReal(:,3),'bo');
% plot3(GaussNatNode(:,1),GaussNatNode(:,2),GaussNatNode(:,3),'rx');

axis equal;

%%

% [Ng,Npg,Nqg,Nrg,...
%     dNdpg,dNdqg,dNdrg,...
%     dNpdpg,dNqdqg,dNrdrg...
%     ]=ShapeFunctionOut(GaussNatNode(:,1),GaussNatNode(:,2),GaussNatNode(:,3),NatNode);
% 
% [N,Np,Nq,Nr,...
%     dNdp,dNdq,dNdr,...
%     dNpdp,dNqdq,dNrdr...
%     ]=ShapeFunctionOut(NatNode(:,1),NatNode(:,2),NatNode(:,3),NatNode);

%%
Xg=zeros(8,1);
Yg=zeros(8,1);
Zg=zeros(8,1);

for n1=1:8
    
   p=GaussNatNode(n1,1);
   q=GaussNatNode(n1,2);
   r=GaussNatNode(n1,3);
   [Ng,Npg,Nqg,Nrg,...
    dNdpg,dNdqg,dNdrg,...
    dNpdpg,dNqdqg,dNrdrg...
    ]=ShapeFunctionOut(p,q,r,NatNode);
   Xg(n1)=Ng.'*NodesReal(:,1);
   Yg(n1)=Ng.'*NodesReal(:,2);
   Zg(n1)=Ng.'*NodesReal(:,3);
end

plot3(Xg,Yg,Zg,'rx');
xnmat=zeros(8,8);
for n1=1:8
[xn,dndloc]=kshapes8(GaussNatNode(n1,1),GaussNatNode(n1,2),GaussNatNode(n1,3),NatNode);
xnmat(n1,:)=xn;
end

n1=5;
[xn,dndloc]=kshapes8(GaussNatNode(n1,1),GaussNatNode(n1,2),GaussNatNode(n1,3),NatNode);
xj=NodesReal.'*dndloc;
xjinv=inv(xj);
%%
dndx=dndloc*xjinv;

xnmatI=inv(xnmat);

XYZ2=xnmatI*[Xg,Yg,Zg];

plot3(XYZ2(:,1),XYZ2(:,2),XYZ2(:,3),'gp');